config/routes.rb
Rails.application.routes.draw do
  root to: 'space_stations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :space_stations do
    resources :attachment_spaces, only: [:update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment_space.rb
class AttachmentSpace < ApplicationRecord
  belongs_to :space_station
  belongs_to :component, optional: true
end

app/models/component.rb
class Component < ApplicationRecord
  has_many :space_stations, through: :attachment_spaces
  validates :image_url, presence: true
  COMPONENTTYPES =
    ['docking',
     'habitat',
     'laboratory',
     'left-solar',
     'right-solar',
     'telescope',
     'top-solar']
  validates :component_type, presence: true, inclusion: { in: COMPONENTTYPES }
  validates :room, presence: true
end

app/models/crew_member.rb
class CrewMember < ApplicationRecord
  belongs_to :space_station
  validates :name, presence: true
  validates :status, presence: true, inclusion: { in: ['working', 'sleeping', 'enjoying the stars', 'deceased'] }
end

app/models/space_station.rb
class SpaceStation < ApplicationRecord
  has_many :attachment_spaces, dependent: :destroy
  has_many :crew_members, dependent: :destroy
  has_many :components, through: :attachment_spaces
  validates :name, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true }
  validates :power, presence: true, numericality: { only_integer: true }
  after_create :generate_attachment_spaces

  def generate_attachment_spaces
    8.times do
      @attachment_space = AttachmentSpace.new
      @attachment_space.space_station = self
      @attachment_space.save!
    end
    @attachment_space = AttachmentSpace.new
    @attachment_space.space_station = self
    @attachment_space.component = Component.find(1)
    @attachment_space.save!
    3.times do
      @attachment_space = AttachmentSpace.new
      @attachment_space.space_station = self
      @attachment_space.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachment_spaces_controller.rb
class AttachmentSpacesController < ApplicationController

  def update
    @attachment_space = AttachmentSpace.find(params[:attachment_space_id])
    @component = Component.find(params[:component])
    @attachment_space.component = @component
    @space_station = @attachment_space.space_station
    if @attachment_space.save
      update_station_stats
      redirect_to space_station_path(@space_station)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def update_station_stats
    @space_station.capacity += @component.room
    @space_station.power += @component.power_generated
    @space_station.save
  end

  def attachment_space_params
    params.require(:attachment_space).permit(:component)
  end
end

app/controllers/space_stations_controller.rb
class SpaceStationsController < ApplicationController
  before_action :set_space_station, only: [:show, :edit, :update, :destroy]

  def index
    @space_stations = SpaceStation.all
  end

  def show
    # @attachment_space = AttachmentSpace.new
    @attachment_spaces = @space_station.attachment_spaces.order("id ASC")
    @top_row = @attachment_spaces.where(id: @attachment_spaces.first.id..(@attachment_spaces.last.id - 6))
    @bottom_row = @attachment_spaces.where(id: (@attachment_spaces.last.id - 5)..@attachment_spaces.last.id)
  end

  def new
    @space_station = SpaceStation.new
  end

  def create
    @space_station = SpaceStation.new(space_station_params)
    @space_station.capacity = 1
    @space_station.power = 10
    if @space_station.save
      redirect_to space_station_path(@space_station)
    else
      render new_space_station_path
    end
  end

  def edit
  end

  def update
    @space_station.update(space_station_params)
    # @component = Component.find(params[:attachment_space][:component_id])
    redirect_to space_station_path(@space_station)
  end

  def destroy
    @space_station.destroy
    redirect_to space_stations_path
  end

  private

  def space_station_params
    params.require(:space_station).permit(:name)
  end

  def set_space_station
    @space_station = SpaceStation.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpacestationBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/space_stations/edit.html.erb
<h1>Rename Space Station</h1>
<%= simple_form_for @space_station do |f| %>
  <%= f.input :name %>
  <%= f.submit "Confirm Change" %>
<% end %>

app/views/space_stations/index.html.erb
<div class="space-container">
  <h1>Space Stations</h1>
  <% @space_stations.each do |station| %>
    <div class="index-card">
      <h2><%= station.name %></h2>
      <%= link_to "[Visit]", space_station_path(station) %>
    </div>
  <% end %>

  <%= link_to "[Build a New Space Station]", :new_space_station %>
</div>

app/views/space_stations/new.html.erb
<div class="space-container">
  <h1>Build a Space Station</h1>
  <%= simple_form_for @space_station do |f| %>
    <%= f.input :name %>
    <%= f.submit "Launch Docking Module" %>
  <% end %>
</div>

app/views/space_stations/show.html.erb
<div class="space-container">
  <h1><%= @space_station.name %></h1>
  <h3>Crew Capacity: <%= @space_station.capacity %></h3>
  <% if (@space_station.power < 0) %>
    <h3>Current Power Output: <strong>INSUFFICIENT</strong> *Install Solar Modules Immediately*</h3>
  <% else %>
    <h3>Current Power Output: <%= @space_station.power %> kWh</h3>
  <% end %>

  <div class="station-container">
    <% @top_row.each do |attachment_space| %>
      <div class="station-module-card">
        <% if attachment_space.component.present? %>
          <%= image_tag attachment_space.component.image_url %>
        <% elsif @attachment_spaces.where(id: (attachment_space.id + 6), component_id: 1..2).present? %>
          <%= form_with(url: space_station_attachment_space_path(attachment_space.id), local: true, method: :patch) do |f| %>
          <%= f.hidden_field(:attachment_space_id, value: attachment_space.id) %>
          <%= f.submit "[Attach Module]" %>
          <%= f.collection_select :component, Component.where(id: 6..7), :id, :component_type %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <% @bottom_row.each do |attachment_space| %>
      <div class="station-module-card">
        <% if attachment_space.component.present? %>
          <%= image_tag attachment_space.component.image_url %>
        <% elsif attachment_space.id == @bottom_row.first.id %>
          <%= form_with(url: space_station_attachment_space_path(attachment_space.id), local: true, method: :patch) do |f| %>
          <%= f.hidden_field(:attachment_space_id, value: attachment_space.id) %>
          <%= f.submit "[Attach Module]" %>
          <%= f.collection_select :component, Component.where(id: 4), :id, :component_type %>
          <% end %>
        <% elsif attachment_space.id == @bottom_row.last.id %>
          <%= form_with(url: space_station_attachment_space_path(attachment_space.id), local: true, method: :patch) do |f| %>
          <%= f.hidden_field(:attachment_space_id, value: attachment_space.id) %>
          <%= f.submit "[Attach Module]" %>
          <%= f.collection_select :component, Component.where(id: 5), :id, :component_type %>
          <% end %>
        <% else %>
          <%= form_with(url: space_station_attachment_space_path(attachment_space.id), local: true, method: :patch) do |f| %>
          <%= f.hidden_field(:attachment_space_id, value: attachment_space.id) %>
          <%= f.submit "[Attach Module]" %>
          <%= f.collection_select :component, Component.where(id: 2..3), :id, :component_type %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="back">
    <%= link_to "[Return to Earth]", space_stations_path %>
  </div>
</div>